apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-app
  title: python flask template
  description: Provisions a minimalistic flask application with techdocs support
spec:
  owner: development
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - component_id
        - environmet
      properties:
        component_id:
          title: Component name
          type: string
          description: Provide a component (microservice) name
          pattern: '^[a-zA-Z][a-zA-Z0-9-_]+$'
        environmet:
          title: Environment
          type: string
          description: Environment where the component will be deployed
          enum:
            - dev
            - syt
            - prd

  steps:
    - id: fetchBase
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{ parameters.component_id }}
          app_env: ${{ parameters.environmet }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: This is ${{parameters.component_id}}
        repoUrl: github.com?owner=ruenpinzon-sketch&repo=${{parameters.component_id}}
        protectDefaultBranch: false

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
