
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-app
  title: python flask template
  description: Provisions a minimalistic Flask application with TechDocs support
spec:
  owner: development
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - component_id
        - environment
      properties:
        component_id:
          title: Component name
          type: string
          description: Provide a component (microservice) name
          pattern: '^[a-zA-Z][a-zA-Z0-9-_]+$'
        environment:
          title: Environment
          type: string
          description: Environment where the component will be deployed
          enum:
            - dev
            - syt
            - prd

  steps:
    - id: fetchBase
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{ parameters.component_id }}
          app_env: ${{ parameters.environment }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: This is ${{ parameters.component_id }}
        # Formato de repoUrl: host?owner=<org-or-user>&repo=<repo-name>[&workspace=<enterprise>&branch=<branch>]
        repoUrl: github.com?owner=rubenpinzon-sketch&repo=${{ parameters.component_id }}
        protectDefaultBranch: false
        # Opcionalmente puedes fijar la rama por defecto si tu plantilla asume 'main':
        # defaultBranch: main
        # Si quieres visibilidad privada:
        # repoVisibility: private
        # Si quieres agregar colaboradores:
        # collaborators:
        #   - team: devs
        #     permission: push

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}